src/NewLabsTest/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NewLabsTest.ViewModels
{
    public class UserViewModel
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        [DisplayFormat(DataFormatString = @"{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Birthday { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}

src/NewLabsTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace NewLabsTest.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/NewLabsTest/Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NewLabsTest.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NewLabsTest.Controllers
{
    public class ImportController : Controller
    {
        private readonly IImportService _importService;
        public ImportController(IImportService importService)
        {
            _importService = importService;
        }

        [Route("import")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("import")]
        public async Task<JsonResult> UploadFiles(IFormFile file, int batchSize)
        {
            bool result;
            using (StreamReader sr = new StreamReader(file.OpenReadStream()))
            {
                result = await _importService.ImportDataAsync(sr, batchSize);
            }
            
            return Json(new { result, message = "the files are uploaded" });
        }
    }
}

src/NewLabsTest/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NewLabsTest.Domain.Models;
using NewLabsTest.Services;
using NewLabsTest.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NewLabsTest.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IMapper _mapper;

        public UserController(IUserService userService, IMapper mapper)
        {
            _userService = userService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> LoadData()
        {
            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();

            // Skip number of Rows count  
            var start = Request.Form["start"].FirstOrDefault();

            // Paging Length 10,20  
            var length = Request.Form["length"].FirstOrDefault();

            // Sort Column Name  
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();

            // Sort Column Direction (asc, desc)  
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

            // Search Value from (Search box)  
            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            long recordsTotal = await _userService.LongCount();

            //Paging   
            var list = await _userService.GetList(sortColumn, sortColumnDirection, skip, pageSize);
            var data = _mapper.Map<IEnumerable<User>, IEnumerable<UserViewModel>>(list);

            //Returning Json Data  
            return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var user = await _userService.GetUserById(id);
            var model = _mapper.Map<User, UserViewModel>(user);
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserViewModel model)
        {
            var user = _mapper.Map<UserViewModel, User>(model);
            var result = await _userService.UpdateUser(user);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await _userService.GetUserById(id);
            var result = await _userService.DeleteUser(user);
            return RedirectToAction("Index");
        }
    }
}

src/NewLabsTest/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/NewLabsTest/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/NewLabsTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



<div class="row">
    <div class="col-md-3">
        <h2>Test Application</h2>
        <ul>
            <li><a asp-controller="Import">Import CSV</a> </li>
            <li><a asp-controller="User">List of Users</a></li>
        </ul>
    </div>
    
</div>

src/NewLabsTest/Views/Import/Index.cshtml
<div class="row">
    <div>
        <h2>Import data from CSV</h2>
        <p>batch size:</p>
        @Html.TextBox("batchSize", 10000, null, new { type = "number" })
        <br/><br />
        @*<input name="batchSize" id="batchSize" value="10000" type="number"/>*@
        <div style="position: relative; width: 296px; background: #f0f0f0">
            <div id="progress" style="background: blue; height: 20px; width: 0"></div>
        </div>
        <input type="file" id="file"/>
        <br />
        <button>upload</button>
        <br />
        <div id="loading">
            <p><img src="/images/load.gif" /> Please Wait...</p>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function() {
            $('#loading').hide();
        });
        $("button").click(function () {
            $('#loading').show();
            var progressEle = $("#progress");
            progressEle.css("background", "blue");

            var data = document.getElementById("file").files[0];
            var batchSize = $("#batchSize").val();

            var formData = new FormData();
            formData.append("file", data);
            formData.append("batchSize", batchSize);

            $(this).hide();

            $.ajax({
                url: "import",
                data: formData,
                processData: false,
                contentType: false,
                type: "POST",
                xhr: function() {
                    var xhr = new window.XMLHttpRequest();
                    xhr.upload.addEventListener("progress",
                        function(evt) {
                            if (evt.lengthComputable) {
                                var progress = Math.round((evt.loaded / evt.total) * 100);
                                progressEle.width(progress + "%");
                            }
                        },
                        false);
                    return xhr;
                },
                success: function (data) {
                    if (data.result == 1) {
                        progressEle.css("background", "green");
                        $("button").show();
                        $('#loading').hide();
                    }
                }
            });
        });
    </script>
}

src/NewLabsTest/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewLabsTest</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NewLabsTest</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - NewLabsTest</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/NewLabsTest/Views/User/Edit.cshtml
@model NewLabsTest.ViewModels.UserViewModel

@{
    ViewData["Title"] = "Edit user";
}
<link href="~/lib/datetimepicker/jquery.datetimepicker.css" rel="stylesheet" />
<link href="~/lib/datetimepicker/build/jquery.datetimepicker.min.css" rel="stylesheet" />

<h4>UserViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="Id" id="Id" hidden="hidden" Value="@Model.Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" type="datetime" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/lib/datetimepicker/jquery.datetimepicker.js"></script>
    <script src="~/lib/datetimepicker/build/jquery.datetimepicker.full.js"></script>
    <script>
        $(document).ready(function () {
            $("#Birthday").datetimepicker({
                timepicker: false,
                format: 'd.m.Y'
            });  
            jQuery.datetimepicker.setLocale('ru');

        })
    </script>
}

src/NewLabsTest/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Users";
}

<link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap.min.css" />
<link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.jqueryui.min.css" />

<div class="row">
    <div class="col-md-12">
        <h2>List of Users</h2>
        
        <div class="container">
            <br />
            <div style="width:90%; margin:0 auto;">
                <table id="table" class="dataTable table table-striped table-bordered nowrap" width="100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Birthday</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>  
    </div>
</div>


@section Scripts {
    <script src="~/lib/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/media/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/moment/moment.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').dataTable({
                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter" : false,
                "orderMulti": true, // for disable multiple column at once
                "button": [
                    'copy', 'excel', 'pdf'
                ],
                "ajax": {
                    "url": "/user/loaddata",
                    "type": "POST",
                    "datatype": "json"
                },
                "columnDefs":
                [
                    {
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    }
                ],
                "columns": [
                    { "data": "Id", "name": "Id", "autoWidth": true },
                    { "data": "Name", "name": "Name", "autoWidth": true },
                    {
                        "data": "Birthday", "name": "Birthday", "autoWidth": true, "type": "date ",
                        render: function (d) {
                            return moment(d).format("DD.MM.YYYY");
                        }
                    },
                    { "data": "Email", "name": "Email", "autoWidth": true },
                    { "data": "Phone", "name": "Phone", "autoWidth": true },
                    {
                        "render": function(data, type, full, meta) {
                            return '<a class="btn btn-info" href="/user/edit/' + full.Id + '">Edit</a>';
                        }
                    },
                    {
                        data: null,
                        render: function(data, type, row) {
                            return "<a href='#' class='btn btn-danger' onclick=DeleteData('" +
                                row.Id +
                                "'); >Delete</a>";
                        }
                    }
                ]
            });
            
        });
        
        function DeleteData(userId) {
            if (confirm("Are you sure you want to delete ...?")) {
                Delete(userId);
            } else {
                return false;
            }
        }


        function Delete(userId) {
            var url = "user/Delete";

            $.post(url,
                { ID: userId },
                function(data) {
                    if (data) {
                        var oTable = $('#table').DataTable();
                        oTable.draw();
                    } else {
                        alert("Something Went Wrong!");
                    }
                });
        }
    </script>
}